---
kind: Template
apiVersion: v1
parameters:
- name: MONGODB_ADMIN_PASSWORD
  generate: expression
  from: '[a-zA-Z0-9]{16}'
- name: MONGODB_USER
  from: 'user[0-9]{3}'
  generate: expression
- name: MONGODB_PASSWORD
  from: '[a-zA-Z0-9]{16}'
  generate: expression
- name: MONGODB_KEYFILE
  value: QTVUXzZXeDc5QmQ3ZW9HMWJWTHAuRVBOLWlJMV82YlNwbXJVZU9IbWtuS0VwOC1Yd1ZpTUhaaixTdTU1d0NJV2NyVnhCSVVEV1V0SzU5cU1GSGUxdllOay52Q3JjdDdqUVEyQUVxa2VUazlPTTRXUXdhOFA4dllHbEFma2RxVjdYRFFwLHZuYVRRay5jR2tiS0ZWeUtRM3Y5eVVRQXlRYkdlR2RCS04wNUVSRWdXQ2csUHMsQXEsTEZ3UnM6UyxKbllZZm1CZlhheXMzTnVRdW8zOmdRWlQsYjdLZVAxa1Fxck1LLFNTN2x1cmJoVmF2VF9WaHBaNyxnTGlZNTdYajlKYWxmYjhJSzhoSkpHQkVROFRWNTVfMTNSOFRsU042LEZaTVJGeHlKUW5LQ0lwdTksTFBtUmEtOXhQWW4wN295UG4yRU8zenRTMlc5R3FtLV9RM0hRd1JPUEJzRnZFTC5WLm05RXVPSmJsdUJPVnBGU0NkZkZVcFUuZHVCU1FzQW1zSDJoMHpQbG1JT2JuM0xEUVNCUzlPNyxiZENUTGRIcywubmQyTnV6RnMtRTMtVFpDMi5IUUVxY0NKNHA1cVgzeGoxSlc5Ti1OdzRjZWNjSkdxUzVNUXNKNGNHX1ZrVl9LckxHZGZnWS5FSHdKZUgtRE0yOUcuSWlKRTM2UTUtLXFySm40cG1oOkgzVVZvSUVDNkF5cm1lSzpBSVdaSnB0bS5WYkoxNnZZcHJrNHcuMV9mNGc6SkotS29uZXNScWM2dEwxeGhUWU1ISng1c2lmS0l1LmJmLS0zMmdTdjRrei55VlJVOnVYT0xfWEZLd2tnYmdrbVVaa1lCZDlReS14dTlOQ1M1RjR6UzY3X09FeW5uVVB6ajhjb3ZpZG05Vk04bTNVeDpQQjgxOjdQWnZmaTouMi5vRmpOLUYyVkIyaldHdkZhcix4LEFTLjgwZXEtT1FFVG9zZTJHZjFNWHosOHE2ZGt1Z3BRejVIRGd4dDp2
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: "rocketchat"
    labels:
      app: rocketchat
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    replicas: 1
    test: false
    selector:
      matchLabels:
        app: rocketchat
    template:
      metadata:
        labels:
          app: rocketchat
      spec:
        volumes:
        - name: rocketchat-volume-1
          emptyDir: {}
        containers:
        - name: rocketchat
          image: registry.connect.redhat.com/rocketchat/rocketchat:1.1.1-19
          ports:
          - containerPort: 3000
            protocol: TCP
          env:
          - name: MONGO_URL
            value: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@rocketchat-mongodb:27017/rocketchat"
          - name: MONGO_OPLOG_URL
            value: "mongodb://admin:${MONGODB_ADMIN_PASSWORD}@rocketchat-mongodb:27017/local?authSource=admin&replSet=rs0"
          resources: {}
          volumeMounts:
          - name: rocketchat-volume-1
            mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}


- kind: Service
  apiVersion: v1
  metadata:
    name: rocketchat
    labels:
      app: rocketchat
  spec:
    ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
    selector:
      app: rocketchat
    type: ClusterIP
    sessionAffinity: None

- kind: Route
  apiVersion: v1
  metadata:
    name: rocketchat
    labels: 
      app: rocketchat
  spec:
    to:
      kind: Service
      name: rocketchat
    port:
      targetPort: 3000-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect


# tasks file for mongodb
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: rocketchat-mongodb
    labels:
      app: rocketchat
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

- apiVersion: v1
  kind: Secret
  metadata:
    name: mongodb-secret
    template.openshift.io/base64-expose-username: "{.data['username']}"
    template.openshift.io/base64-expose-password: "{.data['password']}"
    template.openshift.io/base64-expose-admin_password: "{.data['admin_password']}"
    template.openshift.io/base64-expose-keyfile: "{.data['keyfile']}"
    labels:
      app: rocketchat
  type: Opaque
  stringData:
    username: ${MONGODB_USER}
    password: ${MONGODB_PASSWORD}
    admin_password: ${MONGODB_ADMIN_PASSWORD}
    keyfile: ${MONGODB_KEYFILE}

- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    name: rocketchat-mongodb
    labels:
      app: rocketchat
      service: rocketchat-mongodb
  spec:
    updateStrategy:
      type: RollingUpdate
    replicas: 1
    test: false
    selector:
      matchLabels:
        service: rocketchat-mongodb
    template:
      metadata:
        labels:
          service: rocketchat-mongodb
      spec:
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: rocketchat-mongodb
        containers:
        - name: mongodb
          image: registry.access.redhat.com/rhscl/mongodb-36-rhel7:1-45
          command:
            - '/usr/bin/run-mongod-replication'
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
          - name: MONGODB_DATABASE
            value: rocketchat
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: password
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: admin_password
          - name: MONGODB_REPLICA_NAME
            value: rs0
          - name: MONGODB_KEYFILE_VALUE
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: keyfile
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - name: mongodb-data
            mountPath: "/var/lib/mongodb/data"
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities: {}
            privileged: false
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}

- kind: Service
  apiVersion: v1
  metadata:
    name: rocketchat-mongodb
    labels:
      app: rocketchat
      service: rocketchat-mongodb
  spec:
    ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
    selector: 
      service: rocketchat-mongodb
    type: ClusterIP
    clusterIP: None